# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.6
  # - nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
addons:
  apt:
    packages:
    - libzmq3
before_script:
  - julia -e 'Pkg.add("Rotations"); Pkg.checkout("Rotations", "tk/fix-perp-allocs")'
  - julia -e 'Pkg.add("OSQP"); Pkg.checkout("OSQP")'
  - julia -e 'Pkg.clone("https://github.com/tkoolen/SimpleQP.jl")'
  - julia -e 'Pkg.add("RigidBodyDynamics"); Pkg.checkout("RigidBodyDynamics.jl")'
# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("QPControl"); Pkg.test("QPControl"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("QPControl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
